
name: Linux Build

on: push

jobs:
  build:
    name: Build on Ubuntu
    runs-on: macos-12
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: 2ff845c2e033bd0ff64b5b6aa6063a1f8f65aa32
    - name: Install dependencies
      run: brew install llvm
    - name: Build HandBrake Linux
      run: |
        pip install scan-build
        export PATH="/usr/local/opt/llvm/bin:$PATH"         
        make SDKROOT=macosx.internal
